#!/bin/sh
# Copyright 2009 Jeremy Thurgood <firxen+rinkhals@gmail.com>
# GPL - see COPYING for details
#
# Usage: darwin-py2app

OFA_VERSION=`PYTHONPATH=. python -c "from gamelib import version; print version.VERSION_STR"`
BUILD_FOLDER="foxassault-${OFA_VERSION}"
DMG_NAME="${BUILD_FOLDER}.dmg"
PY2APP_LOG="py2app.log"

echo "=== Setting up build environment ==="

rm -rf build
mkdir build
mkdir dist

for f in gamelib scripts data setup.py; do
    svn export $f build/$f
done

cd build

unzip ../lib/pgu-*.zip
mv pgu-*/pgu .
mkdir -p share/pgu
mv pgu-*/data/themes share/pgu
rm -rf pgu-*
find data -name '*.svg' -delete

echo ""
echo "=== Running python setup.py ==="
echo "  Fox Assault version: ${OFA_VERSION}"
echo "  Writing log to ${PY2APP_LOG}"

# python setup.py py2app >${PY2APP_LOG} 2>&1
python setup.py py2app

echo ""
echo "=== Removing useless cruft that just takes up space ==="
echo ""

for dir in docs examples tests; do
    find "dist/${BUILD_FOLDER}" -path "*/Resources/lib/*/pygame/${dir}/*" -delete
done

echo "=== Building DMG ==="
echo ""

hdiutil create -srcfolder dist/${BUILD_FOLDER}/*.app/ dist/${DMG_NAME}
mv dist/* ../dist/
cd ..

echo ""
echo "=== Done ==="
echo ""
du -sh dist/* | sed 's/^/   /'
echo ""

